sudo: false
language: go
script:
  - cd hystrix
  - go test -race
go:
  - 1.3.3
  - 1.4.3
  - 1.5.4
  - 1.6.1
  - 1.6.2
  - 1.6.3
  - 1.6.4
  - 1.7.1
  - 1.7.2
  - 1.7.3
  - 1.7.4
  - tip
env:
  global:
    - GORACE="halt_on_error=1"