language: go
sudo: false
install:
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golang/lint/golint
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/cactus/go-statsd-client/statsd
  - go get github.com/rcrowley/go-metrics
  - go get github.com/DataDog/datadog-go/statsd

script:
  - cd hystrix
  - go test -race
go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip
env:
  global:
    - GORACE="halt_on_error=1"
